### ISSUE TITLE
Styles not being applied

### ISSUE THREAD

**Issue by ignacio-dev** [guoyunhe/shopify-hydrogen-material-ui-template#1]
After installing and running ```npm run dev```, the pages show on the browser, but all the elements are completely un-styled.

<img width="850" alt="Screenshot 2024-04-30 at 16 55 30" src="https://github.com/guoyunhe/shopify-hydrogen-material-ui-template/assets/60653072/59a5e1b6-b5f7-4354-b3cb-8a8ed6dcde06">

**Comment by guoyunhe** [comment]
That is right. It is not implemented and discontinued. You can find some other templates for better start point.
